// NOTE: this file is auto-generated by Construct
declare class IAnyProjectLayerEffects extends Array<IEffectInstance> {
	MyCustomEffect?: IEffectInstance
}

declare class IAnyProjectLayer extends ILayer {
		effects: IAnyProjectLayerEffects;
}